### ISSUE TITLE
ساعت تابستانی

### ISSUE THREAD

**Issue by R9TRH** [alireza1219/advanced-amoozeshyar#1]
سلام داداش. می‌دونم جاش نیست ولی نتونستم جای دیگه ای پیدا کنم
میتونی فایل tzdata بر پایه 2023c برام بسازی؟ سیستمشو ندارم ولی گوشیم لازم دارتش. اون نسخه که ضمیمه سایتت کردی جواب نداد رو گوشیم. اندرویدم ۱۳ اما ساعتم خراب😂

**Comment by alireza1219** [comment]
سلام و درود بر شما! امیدوارم که حالتون عالی باشه.
ایرادی نداره 😅
تا جایی که اطلاع دارم و خاطرم هست ساختار فایل tzdata بعد از اندروید 7.x دچار تغییرات گسترده‌ای شده و این روش دیگر جوابگو نیست.
اما اگر از نسخه‌های اخیر اندروید مثل اندروید ۱۳ که فرمودید استفاده می‌کنید نیازی به کامپایل مجدد ندارید، و میتونید مستقیما از مخازن گوگل فایل tzdata مربوطه رو دانلود کنید. برای مثال نیم‌نگاهی به [اینجا](https://android.googlesource.com/platform/system/timezone/+/74d520b7e7284eb84e07c8ea40d4718c46b5d4cd/output_data/iana/) و [اینجا](https://android.googlesource.com/platform/system/timezone/+/master/README.android) داشته باشید.
اگر باز هم به راهنمایی نیاز داشتید از طریق ایمیل در ارتباط باشید، خوشحال میشم کمکتون کنم.
شاد و خندون باشید :)
